### ISSUE TITLE
 Backstage POD unable to start

### ISSUE THREAD

**Issue by dbacademy** [janus-idp/helm-backstage#122]
### Describe the bug

Backstage POD unable to start, following error after installing helm chart from the openshift developer console 

Backend failed to start up Error: Missing required config value at 'backend.auth.keys[0].secret'

A clear and concise description of what the bug is. (provide screenshots if applicable)

### What are the steps to reproduce this bug?

1. …
2. …
3. …

**Comment by tumido** [comment]
Hi @dbacademy, this should be resolved now. We've updated the default image.
