### ISSUE TITLE
Use a PVC-based generic ephemeral volume to store dynamic plugins by default, instead of an emptyDir.

### ISSUE THREAD

**Issue by Zaperex** [janus-idp/helm-backstage#146]
Use a PVC-based generic ephemeral volume to store dynamic plugins by default, instead of an emptyDir.

This requires adding general ephemeral volumes in the Upstream backstage helm chart, which requires updating the reference to the `kubernetes` schema to an up-to-date schema.

**Comment by davidfestal** [comment]
Upstream PR https://github.com/backstage/charts/pull/150 would be the first part of this.
When it is available to the Janus helm chart, we'll be able to change the default value in the Janus chart default values.
