### ISSUE TITLE
Unable to upgrade configuration when deployed from OpenShift web console

### ISSUE THREAD

**Issue by kadel** [janus-idp/helm-backstage#151]
### Describe the bug

When trying to upgrade RHDH deployment configuration done via Helm Chart  in OpenShift console, it fails with
```
Backend failed to start up Error: Missing required config value at 'backend.database.client'
```

### What are the steps to reproduce this bug?

https://github.com/janus-idp/helm-backstage/assets/57206/62cdfdb2-e156-4bff-b00e-69a5f3e92271

### Versions of software used and environment
using `1.0-163-CI` from https://gist.github.com/nickboldt/a8483eb244f9c4286798e85accaa70af

**Comment by Zaperex** [comment]
Got the same issue with the `1.0-187-CI` chart from https://gist.githubusercontent.com/rhdh-bot/63cef5cb6285889527bd6a67c0e1c2a9/raw/6bc94990de28202baaad173fc9e18061b375e9f3/index.yaml. 
It seems the `upstream.backstage.command` field gets overwritten to `["node", "packages/backend"]` (default should be `[]`) after using the front view to configure the values, which seems to override the entrypoint and arguments of the image.

**Comment by tumido** [comment]
This is really funny, Just opening and closing the form view, changes values.. And expanding sections does that again.. 😄 


https://github.com/janus-idp/helm-backstage/assets/7453394/692c5f80-60c6-4e43-b3b0-f62cda9a035e
