### ISSUE TITLE
Simplify the definition of the  application host name

### ISSUE THREAD

**Issue by dmartinol** [janus-idp/helm-backstage#167]
### What do you want to improve?
Simplify the definition of the  application host name for a chart deployer.

### What is the current behavior?
The chart deployer must specify the application host using either `global.host` or `global.clusterRouterBase`.
The latter parameter is basically requesting the user to specify a cluster configuration that we can also extract from the cluster itself with a lookup function.

### What is the new behavior?
In the `janus-idp.hostname` template function, extend the [exit condition](https://github.com/janus-idp/helm-backstage/blob/a20e258fa478970baf4a1db2ac1e6bae1e3332de/charts/backstage/templates/_helpers.tpl#L9C6-L9C6) with a further attempt to lookup the cluster domain from the configuration, as in:
`oc get ingress.config.openshift.io/cluster -oyaml | yq '.spec.domain'`
If the configuration is found, then we can use it as a last resort option.

**Comment by masayag** [comment]
@Zaperex can you see if this one is valid and if it can be contributed?

**Comment by Zaperex** [comment]
@masayag I tested on openshift local and verified that the relevant hostname information can be extracted from the cluster with a lookup function. I'll add the PR for it right now.

**Comment by dmartinol** [comment]
Thank you @Zaperex!
