### ISSUE TITLE
[CRC] Backend failed to start up TypeError [ERR_INVALID_URL]: Invalid URL

### ISSUE THREAD

**Issue by pfeifferj** [janus-idp/helm-backstage#18]
when using the default crc base url (*.apps-crc.testing/), the URL check will fail, resulting in a container CrashLoopBackOff

`Backend failed to start up TypeError [ERR_INVALID_URL]: Invalid URL`

**Comment by sabre1041** [comment]
@pfeifferj the `backstage.baseUrl` parameter should include the protocol and hostname of the backstage instance. For example, `https://backstage-backstage. apps-crc.testing`
