### ISSUE TITLE
add config option to optionally create `ServiceMonitor` resource

### ISSUE THREAD

**Issue by kadel** [janus-idp/helm-backstage#96]
- `ServiceMonitor` instructs OpenShift Monitoring stack (Prometheus Operator) to scrape metrics (https://github.com/janus-idp/backstage-showcase/pull/469) from Backstage. 

epic: https://github.com/janus-idp/backstage-showcase/issues/229

**Comment by tumido** [comment]
We support this via: `upstream.metrics.serviceMonitor.enabled=true`

https://github.com/backstage/charts/blob/main/charts/backstage/templates/servicemonitor.yaml
